# Generated by Django 4.1.6 on 2023-02-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_sintomas_paciente_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sintomas',
            name='temperatura',
            field=models.CharField(max_length=6),
        ),
    ]
