# Generated by Django 4.1.6 on 2023-02-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_sintomas_temperatura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sintomas',
            old_name='nauseasinfec_oid',
            new_name='infec_oid',
        ),
        migrations.AddField(
            model_name='sintomas',
            name='nauseas',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
