# Generated by Django 4.1.6 on 2023-02-19 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_sintomas_boca_alter_sintomas_cabeza_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sintomas',
            name='convulsion',
        ),
        migrations.RemoveField(
            model_name='sintomas',
            name='infec_oid',
        ),
    ]
