# Generated by Django 4.1.6 on 2023-02-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_sintomas_convulsion_remove_sintomas_infec_oid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='tipo_lesion1',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_lesion2',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_lesion',
            field=models.CharField(max_length=30),
        ),
    ]
