# Generated by Django 4.1.6 on 2023-02-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_paciente_tipo_lesion1_paciente_tipo_lesion2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='tipo_lesion1',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='tipo_lesion2',
        ),
    ]
