# Generated by Django 4.1.6 on 2023-02-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_paciente_tipo_lesion1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('tipo1', models.CharField(max_length=30)),
                ('tipo2', models.CharField(max_length=30)),
                ('tipo3', models.CharField(max_length=30)),
            ],
        ),
    ]
